[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[font]
size = 20
normal = { family = "Cascadia Code", style = "Regular" }
bold = { family = "Cascadia Code", style = "Bold" }
italic = { family = "Cascadia Code", style = "Italic" }

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.98


[keyboard]
bindings = [
  { key = "A", mods = "Alt", chars = "\u001ba" },
  { key = "B", mods = "Alt", chars = "\u001bb" },
  { key = "C", mods = "Alt", chars = "\u001bc" },
  { key = "D", mods = "Alt", chars = "\u001bd" },
  { key = "E", mods = "Alt", chars = "\u001be" },
  { key = "F", mods = "Alt", chars = "\u001bf" },
  { key = "G", mods = "Alt", chars = "\u001bg" },
  { key = "H", mods = "Alt", chars = "\u001bh" },
  { key = "I", mods = "Alt", chars = "\u001bi" },
  { key = "J", mods = "Alt", chars = "\u001bj" },
  { key = "K", mods = "Alt", chars = "\u001bk" },
  { key = "L", mods = "Alt", chars = "\u001bl" },
  { key = "M", mods = "Alt", chars = "\u001bm" },
  { key = "N", mods = "Alt", chars = "\u001bn" },
  { key = "O", mods = "Alt", chars = "\u001bo" },
  { key = "P", mods = "Alt", chars = "\u001bp" },
  { key = "Q", mods = "Alt", chars = "\u001bq" },
  { key = "R", mods = "Alt", chars = "\u001br" },
  { key = "S", mods = "Alt", chars = "\u001bs" },
  { key = "T", mods = "Alt", chars = "\u001bt" },
  { key = "U", mods = "Alt", chars = "\u001bu" },
  { key = "V", mods = "Alt", chars = "\u001bv" },
  { key = "W", mods = "Alt", chars = "\u001bw" },
  { key = "X", mods = "Alt", chars = "\u001bx" },
  { key = "Y", mods = "Alt", chars = "\u001by" },
  { key = "Z", mods = "Alt", chars = "\u001bz" }
]
