[font]
normal.family = "Fira Code"
normal.style = "Regular"
size = 22

[window]
padding.x = 10
padding.y = 10
decorations = "None"  # Matches Kitty's hide_window_decorations=yes
opacity = 0.98        # Matches Kitty's background_opacity
startup_mode = "Maximized"

[cursor]
style.shape = "Underline"  # Matches Kitty's cursor_shape=underline
style.blinking = "Off"    # Matches Kitty's disable_ligatures=cursor (no cursor ligature effects)
vi_mode_style = "Underline"

[scrolling]
history = 2000  # Matches Kitty's scrollback_lines

[colors.primary]
background = "#1a1b26"  # Matches Kitty's background
foreground = "#a9b1d6"  # Matches Kitty's foreground

[colors.normal]
black = "#32344a"   # Matches Kitty's color0
red = "#f7768e"     # Matches Kitty's color1
green = "#9ece6a"   # Matches Kitty's color2
yellow = "#e0af68"  # Matches Kitty's color3
blue = "#7aa2f7"    # Matches Kitty's color4
magenta = "#ad8ee6" # Matches Kitty's color5
cyan = "#449dab"    # Matches Kitty's color6
white = "#787c99"   # Matches Kitty's color7

[colors.bright]
black = "#444b6a"   # Matches Kitty's color8
red = "#ff7a93"     # Matches Kitty's color9
green = "#b9f27c"   # Matches Kitty's color10
yellow = "#ff9e64"  # Matches Kitty's color11
blue = "#7da6ff"    # Matches Kitty's color12
magenta = "#bb9af7" # Matches Kitty's color13
cyan = "#0db9d7"    # Matches Kitty's color14
white = "#acb0d0"   # Matches Kitty's color15

[colors.selection]
background = "#7aa2f7"  # Matches Kitty's selection_background
foreground = "#1a1b26"  # Matches Kitty's selection_foreground

[keyboard]
bindings = [
  { key = "C", mods = "Super", action = "Copy" },
  { key = "V", mods = "Super", action = "Paste" },
  { key = "F11", action = "ToggleFullscreen" },
  { key = "A", mods = "Alt", chars = "\u001ba" },
  { key = "B", mods = "Alt", chars = "\u001bb" },
  { key = "C", mods = "Alt", chars = "\u001bc" },
  { key = "D", mods = "Alt", chars = "\u001bd" },
  { key = "E", mods = "Alt", chars = "\u001be" },
  { key = "F", mods = "Alt", chars = "\u001bf" },
  { key = "G", mods = "Alt", chars = "\u001bg" },
  { key = "H", mods = "Alt", chars = "\u001bh" },
  { key = "I", mods = "Alt", chars = "\u001bi" },
  { key = "J", mods = "Alt", chars = "\u001bj" },
  { key = "K", mods = "Alt", chars = "\u001bk" },
  { key = "L", mods = "Alt", chars = "\u001bl" },
  { key = "M", mods = "Alt", chars = "\u001bm" },
  { key = "N", mods = "Alt", chars = "\u001bn" },
  { key = "O", mods = "Alt", chars = "\u001bo" },
  { key = "P", mods = "Alt", chars = "\u001bp" },
  { key = "Q", mods = "Alt", chars = "\u001bq" },
  { key = "R", mods = "Alt", chars = "\u001br" },
  { key = "S", mods = "Alt", chars = "\u001bs" },
  { key = "T", mods = "Alt", chars = "\u001bt" },
  { key = "U", mods = "Alt", chars = "\u001bu" },
  { key = "V", mods = "Alt", chars = "\u001bv" },
  { key = "W", mods = "Alt", chars = "\u001bw" },
  { key = "X", mods = "Alt", chars = "\u001bx" },
  { key = "Y", mods = "Alt", chars = "\u001by" },
  { key = "Z", mods = "Alt", chars = "\u001bz" },
]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "zsh"
args = ["-l", "-c", "tmux new -A -s alacritty zellij"]
