[general]
import = ["$XDG_CONFIG_HOME/alacritty/alacritty.toml"]

[window]
padding.x = 0
padding.y = 0
opacity = 1
decorations = "None"
startup_mode = "Maximized"

[font]
normal.family = "SF Mono"
normal.style = "Regular"
size = 16
