# ~/.tmuxinator/base.yml

name: base
root: ~/Developer
tmux_command: env TERM=screen-256color-italic tmux

windows:
  - editor: e
  - repl:
  - shell:
  - server:
  - dotfiles:
      root: ~/.dotfiles
      panes:
        -
