---
name: help_kitchen
project_root: ~/Work/help_kitchen/helpkitchen
startup_window: shell

on_project_first_start: |
  kill-port 3000 3001 3010 6379
  pg_start --brew >/dev/null
  bundle install && yarn

on_project_stop: |
  kill-port 3000 3001 3010 6379

windows:
- worker: redis-start 6379 & bin/sidekiq --config config/sidekiq.yml
- rails: bin/rails server -b 0.0.0.0 -p 3001
- assets:
    layout: e426,255x19,0,0{39x19,0,0[39x9,0,0,28,39x9,0,10,29],215x19,40,0,27}
    panes:
    - yarn build --watch
    - yarn build:css --watch
    - bin/rails tailwindcss:watch
- console: |
      export DISABLE_SPRING=1
      bin/rails console
- shell:
