---
name: prm
project_root: ~/Work/prm
on_project_first_start: pg_start
windows:
- server:
    layout: even-horizontal
    panes:
      - npm run dev --prefix assets
      - poetry run server
- worker:
    layout: even-horizontal
    panes:
      - redis-start
      - ulimit -Sn 10000 && poetry run worker
- shell: poetry run shell
- bash: poetry run tests
