---
name: tcl-app
project_root: "~/Work/thatcleanlife/thatcleanlife-app"
startup_window: shell

on_project_first_start: |
  kill-port 6379 5001 3000 5432
  sleep 1

on_project_stop: |
  kill-port 6379 5001 3000 5432

windows:
- rails:
    panes:
    - bin/rails server
- sidekiq:
    layout: even-horizontal
    panes:
      - sidekiq:
        - bin/db start
        - bin/sidekiq -C config/sidekiq.yml
      - nutrition-api:
        - cd ../thatcleanlife-nutrition-api
        - bin/rails server
- console:
    panes:
    - bin/rails console
- tests:
    panes:
    - echo bin/test_run
- shell:
    panes:
    - fortune
