---
name: within3-etl
project_root: ~/Work/within3/fabric-data-pipeline
on_project_first_start: pg_start
startup_window: shell

windows:
  - fabric: cd ../fabric-core && ./run all:couchbase:redis
  - worker:
      layout: even-horizontal
      pre_window: redis-start 6380 &
      panes:
        - bundle exec sidekiq --concurrency 5
        - redis-cli
  - etl: bin/rails server
  - console: bin/rails console
  - shell: fortune
