---
name: within3-etl
project_root: ~/Work/within3/fabric-etl
on_project_first_start: pg_start
startup_window: shell

windows:
  - fabric: cd ../fabric-core && ./run all
  - worker:
      layout: even-horizontal
      panes:
        - kill "$(lsof -wnP -i tcp | grep 6380 | awk '{ print $2 }' | sort -u | head -1)" && redis-start 6380 &
        - bin/sidekiq -q default -q callbacks -q extraction -q importation -q enrichment -q serialization -q verification -q loading -q normalization --concurrency 5
  - etl: bin/rails server
  - console: bin/rails console
  - shell: fortune
